### ISSUE TITLE
Unwrapping with postcss-nested

### ISSUE THREAD

**Issue by bboro** [20lives/tailwindcss-rtl#30]
Hi!

Thanks for the useful plugin! I think I'm noticing a bug with unwrapping when using `postcss-nested` plugin.

Consider the following pcss:

```scss
.element-a {
  .element-a-inner {
    .title {
      @apply ps-1;
    }
  }
}
```

This gets compiled into css:

```css
.element-a .element-a-inner [dir="rtl"] .title {
  padding-right: 0.25rem;
}

.element-a .element-a-inner [dir="ltr"] .title {
  padding-left: 0.25rem;
}
```

which seems wrong. I think it should be:

```css
[dir="rtl"] .element-a .element-a-inner .title {
  padding-right: 0.25rem;
}

[dir="ltr"] .element-a .element-a-inner .title {
  padding-left: 0.25rem;
}
```

This ends up breaking some elements' layout as paddings are no longer applied.
